version: '3.8'

services:
  svm_service:
    build:
      context: ./svm_service
    container_name: svm_service
    image: devops-app/svm-service:latest
    volumes:
      - shared_volume:/Nouvarch/shared_volume
    ports:
      - "5001:5001"

  vgg19_service:
    build:
      context: ./vgg19_service
    container_name: vgg_service
    image: devops-app/vgg19-service:latest
    volumes:
      - shared_volume:/Nouvarch/shared_volume
    ports:
      - "5002:5002"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    image: devops-app/frontend:latest
    volumes:
      - shared_volume:/Nouvarch/shared_volume
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    depends_on:
      - svm_service
      - vgg19_service

volumes:
  shared_volume:
